### ISSUE TITLE
Good First Issue: Some Improvements

### ISSUE THREAD

**Issue by eggsy** [florian-lefebvre/shortcuts-app#1]
Hi! I know your app is in its really early stage and I really liked the concept, but just have some small improvements to suggest that'll make your users' job easier when they're using your app.

First of all, I'd like to start with the CSC (code signing certificate) which is I believe some organization offers for free to open source projects. This way you could get rid of SmartScreen errors and Edge's post-download security checks I believe 😅

Here are the list of my actual suggestions:

- [ ] [BUG] Address bar gets cleared after changing pages in the website.
- [ ] Needs shortcuts like Chrome tabs, TAB + 1 to switch to the first shortcut etc.
- [ ] Hide window controls (who need them?)
- [ ] Transitions over the app, like when "Add New Website" modal shows up.
- [ ] Maybe even an option to change the sidebar column (top-right-bottom instead of only left side)!

These are all my suggestions so far. I like your work, keep it  up!

**Comment by florian-lefebvre** [comment]
- [ ] Find a free open source CSC (see https://github.com/florian-lefebvre/shortcuts-app/blob/master/README.md#csc-research)

**Comment by florian-lefebvre** [comment]
> First of all, I'd like to start with the CSC (code signing certificate) which is I believe some organization offers for free to open source projects. This way you could get rid of SmartScreen errors and Edge's post-download security checks I believe 😅

@eggsy If you have links for free CSC, feel free to send them here.

**Comment by eggsy** [comment]
Sadly... This is the developer of the app PreMiD, open-source Discord RPC integration for websites.

![IMG_20210101_152013.jpg](https://user-images.githubusercontent.com/13917975/103438545-f5304300-4c44-11eb-9255-61db48b77b59.jpg)

**Comment by florian-lefebvre** [comment]
Never mind, I'm looking at an alternative solution (codenotary) instead, thank you anyway.
